<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Rulesets\callterminateflow.module" />
    <None Remove="Rulesets\callterminateflow.resources" />
    <None Remove="Rulesets\initial.module" />
    <None Remove="Rulesets\initial.resources" />
    <None Remove="Rulesets\returnwithnullresponse.module" />
    <None Remove="Rulesets\returnwithnullresponse.resources" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Rulesets\callterminateflow.module" />
    <EmbeddedResource Include="Rulesets\callterminateflow.resources" />
    <EmbeddedResource Include="Rulesets\initial.module" />
    <EmbeddedResource Include="Rulesets\initial.resources" />
    <EmbeddedResource Include="Rulesets\returnwithnullresponse.module" />
    <EmbeddedResource Include="Rulesets\returnwithnullresponse.resources" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LogicBuilder.App.AI.Utils" Version="1.0.1-alpha.0.2" />
  </ItemGroup>

</Project>
