<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
		<PackageId>LogicBuilder.App.AI.Utils</PackageId>
		<Authors>BlaiseD</Authors>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>true</WarningsAsErrors>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<Description>Generates agents and their tool collections given an object hierarchy.</Description>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageReleaseNotes>First release.</PackageReleaseNotes>
		<PackageTags>linq expressions</PackageTags>
		<Copyright>Copyright © BPS 2026</Copyright>
		<RepositoryUrl>https://github.com/BpsLogicBuilder/LogicBuilder.App.AI.Utils</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/BpsLogicBuilder/LogicBuilder</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>
		<AssemblyOriginatorKeyFile>..\LogicBuilder.Rules.snk</AssemblyOriginatorKeyFile>
		<SignAssembly>true</SignAssembly>
		<MinVerTagPrefix>v</MinVerTagPrefix>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\icon.png" Pack="true" PackagePath="\" Visible="False" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.2.0" />
		<PackageReference Include="LogicBuilder.App.Utils" Version="1.0.8-alpha.0.1" />
		<PackageReference Include="LogicBuilder.RulesDirector" Version="2.0.6" />
		<PackageReference Include="Microsoft.Agents.AI.Foundry" Version="1.22.0-preview.260918.1" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400" PrivateAssets="All" />
		<PackageReference Include="MinVer" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
